# frozen_string_literal: true

# Writes lib/nohead/operations.rb from openapi.json: the method and path of
# every operation an API key can call. Session-only operations (organizations,
# projects, members, API keys, billing) belong to the web app and are left out.
#
#   rake generate

require "json"

root = File.expand_path("..", __dir__)
spec = JSON.parse(File.read(File.join(root, "openapi.json"), encoding: "UTF-8"))
methods = %w[get post put patch delete]

operations = spec.fetch("paths").flat_map do |path, item|
  methods.filter_map do |method|
    operation = item[method] or next
    security = operation.fetch("security", spec.fetch("security"))
    next unless security.empty? || security.any? { |s| s.key?("apiKey") }

    [operation.fetch("operationId"), method.upcase, path]
  end
end.sort

lines = operations.map do |id, method, path|
  "    #{id.inspect} => [#{method.inspect}, #{path.inspect}],"
end

File.write(File.join(root, "lib/nohead/operations.rb"), <<~RUBY)
  # frozen_string_literal: true

  # Generated by scripts/generate.rb from openapi.json. Do not edit.
  module Nohead
    # Every operation an API key can call: [method, path].
    OPERATIONS = {
  #{lines.join("\n")}
    }.freeze
  end
RUBY
puts "#{operations.size} operations"
